stages:
    - build
    - deploy

compile:
  stage: build
  script: docker build -t tugitlabbot-template .

run:
  stage: deploy
  script:
    - echo -e "docker stop tugitlabbot-container\nexit 0" | bash
    - echo -e "docker rm tugitlabbot-container\nexit 0" | bash
    - >
      docker run -d --restart unless-stopped
      --env TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      --mount type=volume,source=tugitlabbot-volume,target=/app/data
      --name tugitlabbot-container tugitlabbot-template
  environment:
    name: production
  only: 
    - master